[versions]
agp = "8.11.1" # Fdroid can't build apps with agp 8.12.0+ see issue https://forum.f-droid.org/t/f-droid-build-servers-cant-build-modern-android-apps-due-to-outdated-cpus/33065/21
composeWebview = "0.33.6"
kotlin = "2.2.20"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.0"
activityCompose = "1.10.1"
composeBom = "2025.12.00"
kotlinxSerializationJson = "1.8.0"
ksp = "2.2.20-2.0.3" # "kotlinVersion-kspVersion"
hiltAndroid = "2.57.1"
materialKolor = "3.0.0-alpha04"
orgEclipsePahoMqttv5Client = "1.2.5"
datastorePreferences = "1.1.7"
navigationCompose = "2.9.0"
hiltNavigationCompose = "1.2.0"
accompanistPermissions = "0.36.0"
leakcanaryAndroid = "3.0-alpha-8"
acra = "5.13.1"
materialIconsCore = "1.7.8"

[libraries]
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsCore" }
acra-mail = { module = "ch.acra:acra-mail", version.ref = "acra" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
compose-webview = { module = "io.github.kevinnzou:compose-webview", version.ref = "composeWebview" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
org-eclipse-paho-mqttv5-client = { module = "org.eclipse.paho:org.eclipse.paho.mqttv5.client", version.ref = "orgEclipsePahoMqttv5Client" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = {id = "com.google.devtools.ksp", version.ref = "ksp"}
serializarion = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
hilt-android ={id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid"}
android-library = { id = "com.android.library", version.ref = "agp" }
